selected_values = [
    {
        "name": "A-10 Thunderbolt II",
        "type": "attack aircraft",
        "crew": 1,
        "weights": {
            "empty": "23,000 kg (50,700 lb)",
            "maximum_takeoff": "Not specified",
        },
        "range": {"ferry": "4,200 km (2,600 mi)", "combat": "560 km (350 mi)"},
        "weapons": {
            "guns": "GAU-8 Avenger 30mm cannon (7,000 rounds per minute)",
            "missiles": "AGM-65 Maverick, AGM-122 Sidewinder",
            "bombs": "Mark 82, Mark 84, CBU-54/55/77 cluster bombs",
        },
        "avionics": "AN/APG-66T TWS radar, AN/AAS-35 Night Targeting System (NTS)",
        "length": 16,
        "speed": {"max_speed": "670 km/h (416 mph)"},
        "maxrange": "Not specified",
        "engine": "TF34-GE-100 turbofan engine (2x)",
        "climb_rate": "Not specified",
    },
    {
        "name": "Airbus A400M Atlas",
        "type": "military transport aircraft",
        "crew": 4,
        "weights": {
            "empty": "Not specified",
            "maximum_takeoff": "70 tonnes (154,000 lb)",
        },
        "range": {"ferry": "4,630 km (2,877 mi)", "combat": "2,500 km (1,550 mi)"},
        "weapons": "Not applicable",
        "avionics": "Rockwell Collins EVS-2000 head-up displays (HUDs), RDR-45A radar, Thales VSM-500/510 inertial navigation systems (INS)",
        "length": 45,
        "speed": {"max_speed": "720 km/h (447 mph)"},
        "maxrange": "Not specified",
        "engine": "TP4D-6 turboprop engine (4x)",
        "climb_rate": "Not specified",
    },
    {
        "name": "AG600",
        "type": "amphibian aircraft",
        "crew": "Not specified",
        "weights": {"empty": "Not specified", "maximum_takeoff": "53.5 ton"},
        "range": {"ferry": "5700 km", "combat": "Not specified"},
        "weapons": "Not applicable",
        "avionics": "Not specified",
        "length": 37,
        "speed": {"max_speed": "570 km/h"},
        "maxrange": "Not specified",
        "engine": "WJ-6C turboprop engine (4x)",
        "climb_rate": "17.6 m/s",
    },
    {
        "name": "AV-8B Harrier II",
        "type": "Vertical/short takeoff and landing (VTOL/STOL) attack aircraft",
        "crew": 1,
        "weights": {
            "empty": "7,150 kg (15,763 lb)",
            "maximum_takeoff": "14,500 kg (32,000 lb)",
        },
        "range": {
            "ferry": "870 km (540 mi) with external fuel tanks",
            "combat": "Not specified",
        },
        "weapons": {
            "guns": "1 × 25 mm GAU-12 Equalizer rotary cannon",
            "missiles": "AIM-9 Sidewinder, AIM-120 AMRAAM air-to-air missiles, AGM-65 Maverick air-to-surface missiles, precision-guided munitions, gravity bombs, and rocket pods",
            "bombs": "Not specified",
        },
        "avionics": "AN/APG-65 radar, FLIR, night vision devices",
        "length": 14,
        "speed": {"max_speed": "1,110 km/h (687 mph) at low altitude"},
        "maxrange": "Not specified",
        "engine": "Rolls-Royce Pegasus F402-RR-408 (Mk 107) vectored-thrust turbofan",
        "climb_rate": "Not specified",
    },
    {
        "name": "B-1B Lancer",
        "type": "Supersonic strategic heavy bomber",
        "crew": "Not specified",
        "weights": {"empty": "150,000 kg", "maximum_takeoff": "311,130 kg"},
        "range": {"ferry": "Not specified", "combat": "Not specified"},
        "weapons": [
            "AGM-154C Joint Standoff Weapon (JSOW)",
            "AGM-158C Littoral Anti-Ship Missile (LASSM)",
            "AGM-88 HARM (High-speed Anti-Radiation Missile)",
            "GBU-31 JDAM (Joint Direct Attack Munition)",
            "GBU-38 JDAM",
            "Mark 82, Mark 84, and Mark 83 general-purpose bombs",
            "B61 nuclear bombs (currently in phase-out process)",
        ],
        "avionics": "Not specified",
        "length": 26.5,
        "speed": {"max_speed": "Not specified"},
        "maxrange": "Not specified",
        "guns": "Not specified",
        "engine": "4 Ã— General Electric F101-GE-102 turbofan engines",
        "climb_rate": "Not specified",
        "missles": "Not specified",
        "bombs": "Not specified",
    },
    {
        "name": "B-2 Spirit",
        "type": "Stealth bomber",
        "crew": "Not specified",
        "weights": {"empty": "162,000 kg", "maximum_takeoff": "204,111 kg"},
        "range": {"ferry": "11,100 km", "combat": "Not specified"},
        "weapons": [
            "GBU-27 Paveway III laser-guided bombs",
            "GBU-31 JDAM GPS-guided bombs",
            "AGM-154C Joint Standoff Weapon (JSOW)",
            "B61 nuclear bombs",
        ],
        "avionics": "Integrated Defensive Aids System (IDAS)",
        "length": 21.13,
        "speed": {"max_speed": "1,005 km/h"},
        "maxrange": "Not specified",
        "guns": "Not specified",
        "engine": "Not specified",
        "climb_rate": "Not specified",
        "missles": "Not specified",
        "bombs": "Not specified",
    },
    {
        "name": "B-52 Stratofortress",
        "type": "heavy strategic bomber",
        "crew": 6,
        "weights": {
            "empty": "88,200 kg (194,400 lb)",
            "maximum_takeoff": "221,350 kg (488,000 lb)",
        },
        "range": {"ferry": "Not specified", "combat": "8,800 km (5,469 mi)"},
        "weapons": {
            "guns": "Not specified",
            "missiles": {"M117": 35, "GBU-31": 12, "AGM-158 JASSM": 20},
            "bombs": {"AGM-86C CALCM": 20},
        },
        "avionics": "Not specified",
        "length": 45.1,
        "speed": {"max_speed": "Not specified"},
        "maxrange": "16,100 km (10,000 mi)",
        "engine": "Pratt & Whitney TF33-PW-103 turbofan engine (8x)",
        "climb_rate": "Not specified",
    },
    {
        "name": "Be200 Spirit",
        "type": "Amphibious aircraft",
        "crew": "Not specified",
        "weights": {"empty": 3802, "maximum_takeoff": 5670},
        "range": {"ferry": "Not specified", "combat": 1670},
        "weapons": "Not applicable",
        "avionics": "Not specified",
        "length": 12.19,
        "speed": {"max_speed": 328},
        "maxrange": "Not specified",
        "engine": "Pratt & Whitney Canada PW150A turboprop engine (2x)",
        "climb_rate": 5.8,
        "missiles": "Not specified",
        "bombs": "Not specified",
    },
    # First dictionary
    {
        "name": "C-130 Hercules",
        "type": "Military transport aircraft",
        "crew": "6-7",
        "weights": {"empty": "Not specified", "maximum_takeoff": "Not specified"},
        "range": {"ferry": "3,450 km (2,140 mi)", "combat": "Not specified"},
        "weapons": "Not applicable",
        "avionics": "Not specified",
        "length": 29.79,
        "speed": {"max_speed": "Not specified"},
        "maxrange": "Not specified",
        "engine": "4 × Rolls-Royce AE2100D turboprop engines",
        "climb_rate": "Not specified",
        "missiles": "Not specified",
        "bombs": "Not specified",
    },
    # Second dictionary
    {
        "name": "C-17 Globemaster III",
        "type": "Military transport aircraft",
        "crew": "3 (pilot, copilot, loadmaster)",
        "weights": {
            "empty": "88,000 kg (194,000 lb)",
            "maximum_takeoff": "265,350 kg (585,000 lb)",
        },
        "range": {"ferry": "4,440 km (2,759 mi)", "combat": "4,630 km (2,877 mi)"},
        "weapons": {
            "guns": "Not specified",
            "missiles": "AGM-154 Joint Standoff Weapon (JSOW)",
            "bombs": "GBU-31, GBU-38, GBU-54",
        },
        "avionics": "Not specified",
        "length": 56.7,
        "speed": {"max_speed": "830 km/h (516 mph)"},
        "maxrange": "Not specified",
        "engine": "4 × Pratt & Whitney F117-PW-100 turbofan",
        "climb_rate": "Not specified",
        "missiles": "Not specified",
        "bombs": "Not specified",
    },
    {
        "length_abc": 44,
        "name": "Kawasaki C-2",
        "type": "Military transport aircraft",
        "engine": "General Electric CF6-80C2K1F (2x)",
        "weights": {
            "empty": "61,000 kilograms (134,522 pounds)",
            "maximum_takeoff": "142,000 kilograms (313,054 pounds)",
        },
        "range": {
            "maximum_ferry": "9800 kilometers (5,965 miles)",
            "with_30_ton_payload": "6500 kilometers (4,039 miles)",
        },
        "speed": {"cruise_speed": "890 kilometers per hour (553 miles per hour)"},
        "maxrange": "Not specified",
        "guns": "Not specified",
        "engine": "General Electric CF6-80C2K1F (2x)",
        "climb_rate": "Not specified",
        "missles": "Not specified",
        "bombs": "Not specified",
    },
    {
        "length_abc": 75,
        "name": "C-5 Galaxy",
        "type": "Military transport aircraft",
        "crew": "Not specified",
        "weights": {
            "empty": "376,743 lb (171,329 kg)",
            "maximum_takeoff": "837,000 lb (380,114 kg)",
        },
        "range": "4,500 mi (7,200 km)",
        "speed": {"max_speed": "532 mph (856 km/h)"},
        "maxrange": "Not specified",
        "guns": "Not specified",
        "engine": "General Electric TF39-GE-1C (4x)",
        "climb_rate": "Not specified",
        "missles": "Not specified",
        "bombs": "Not specified",
    },
    {
        "length_abc": 17.5,
        "name": "E-2 Hawkeye",
        "type": "Surveillance aircraft",
        "crew": "5 personnel",
        "weights": {
            "empty": "21,772 kg (48,000 lb)",
            "maximum_takeoff": "26,535 kg (58,500 lb)",
        },
        "range": {"ferry": "2960 km (1840 mi)", "combat": "833 km (518 mi)"},
        "speed": "Not specified",
        "maxrange": "Not specified",
        "guns": "Not specified",
        "engine": "Allison T56-A-427 (2x)",
        "climb_rate": "Not specified",
        "missles": "Not specified",
        "bombs": "Not specified",
        "avionics": [
            "AN/APS-145 radar",
            "IFF/SSR interrogator",
            "ESM/RWR system",
            "LINK 11/TADILS data link",
            "Joint Tactical Radio System (JTRS)",
        ],
    },
    {
        "name": "Boeing 737 AEW&C",
        "type": "Airborne early warning and control (AEW&C) aircraft",
        "crew": "12-14",
        "weights": {
            "empty": "42,499 kg (93,700 lb)",
            "maximum_takeoff": "77,519 kg (170,880 lb)",
        },
        "range": {"ferry": "7,730 km (4,809 mi)", "combat": "560 km (348 mi)"},
        "weapons": {
            "guns": "Not specified",
            "missiles": "Not specified",
            "bombs": "Not specified",
        },
        "avionics": "Northrop Grumman AN/APY-2 radar system, Defensive countermeasures only (chaff, flares, EW suite), Electronic intelligence (ELINT), Electronic support measures (ESM), IFF, Link 16, Voice communication",
        "length": 39.95,
        "speed": {"max_speed": "Not specified"},
        "maxrange": "Not specified",
        "engine": "Two CFM56-2C or Rolls-Royce BR715 turbofan engines",
        "climb_rate": "Not specified",
    },
    {
        "name": "Eurofighter Typhoon EF2000",
        "type": "Multirole fighter aircraft",
        "crew": "Not specified",
        "weights": {
            "empty": "10,500 kg (23,150 lb)",
            "maximum_takeoff": "23,500 kg (51,800 lb)",
        },
        "range": {
            "ferry": "1,850 km (1,150 mi)",
            "combat": "550 km (340 mi) at low altitude",
        },
        "weapons": {
            "guns": "1 × 27 mm Mauser BK-27 cannon (500 rounds)",
            "missiles": ["AIM-120 AMRAAM", "IRIS-T", "Meteor", "AIM-9 Sidewinder"],
            "bombs": ["GBU-12 Paveway II", "EGBU-24 Paveway III", "JDAM"],
        },
        "avionics": {
            "radar": "Captor radar",
            "electronic warfare": "Eurofighter Defensive Aids System (DAS)",
        },
        "length": 15.93,
        "speed": {"max_speed": "Mach 2.25 (2,495 km/h; 1,550 mph)"},
        "maxrange": "Not specified",
        "engine": "Eurojet EJ200",
        "climb_rate": "Not specified",
    },  # First aircraft
    {
        "name": "F-117 Nighthawk",
        "type": "Stealth fighter",
        "crew": 1,
        "weights": {
            "empty": "26,700 lb (12,111 kg)",
            "maximum_takeoff": "60,000 lb (27,216 kg)",
        },
        "range": {"ferry": "475 miles (764 km)", "combat": "Not specified"},
        "weapons": {
            "internal_cannon": "M61 Vulcan 20mm cannon (600 rounds)",
            "hardpoints": [
                "(underneath the wings), capable of carrying a variety of weapons",
                "AGM-88 HARM anti-radar missiles",
                "GBU-15/24/27 Paveway laser-guided bombs",
                "GBU-28 JDAM GPS-guided bombs",
                "AGM-130 Standoff Weapon (SLAM)",
            ],
        },
        "avionics": {
            "radar": "AN/APG-78 LPI radar",
            "IRST_system": "AN/AAS-36 Infrared Search and Track (IRST) system",
            "ECM_suite": "AN/ALQ-131 electronic countermeasures (ECM) suite",
        },
        "length": 19.43,
        "speed": {"max_speed": "670 mph (1,078 km/h, Mach 0.85)"},
        "maxrange": "Not specified",
        "engine": "Not specified",
        "climb_rate": "Not specified",
        "missiles": "Not specified",
        "bombs": "Not specified",
    },
    # Second aircraft
    {
        "name": "Grumman Fighter Interceptor",
        "type": "fighter interceptor",
        "crew": 2,
        "weights": {
            "empty": "21,180 kg (46,700 lb)",
            "maximum_takeoff": "33,855 kg (74,650 lb)",
        },
        "range": {"ferry": "1,050 km (650 mi)", "combat": "Not specified"},
        "weapons": {
            "guns": "1x M61 Vulcan 20mm cannon (internal)",
            "missiles": {
                "air-to-air": "AIM-54 Phoenix, AIM-7 Sparrow, AIM-9 Sidewinder, AIM-120 AMRAAM",
                "air-to-surface": "AGM-122 Sidearm, AGM-65 Maverick, AGM-84 Harpoon",
            },
            "bombs": "various Mk.80 series bombs, laser-guided bombs",
        },
        "avionics": {"radar": "AN/APG-74 Pulse Doppler radar"},
        "length": 19.1,
        "speed": {"max_speed": "2,400 km/h (1,500 mph, Mach 2.34)"},
        "maxrange": "Not specified",
        "engine": "Not specified",
        "climb_rate": "152.4 m/s (300 ft/s)",
        "missiles": "Not specified",
        "bombs": "Not specified",
    },
    {
        "name": "McDonnell Douglas F-15 Eagle",
        "type": "fighter aircraft",
        "crew": "Not specified",
        "weights": {
            "empty": "12,055 kg (26,617 lb)",
            "maximum_takeoff": "30,870 kg (68,064 lb)",
        },
        "range": {
            "ferry": "1,960 km (1,218 mi) with internal fuel, expandable with external fuel tanks",
            "combat": "Not specified",
        },
        "weapons": {
            "guns": "1 Ã— M61 Vulcan 20 mm cannon (675 rounds)",
            "air-to-air_missiles": "AIM-7 Sparrow, AIM-9 Sidewinder, AIM-120 AMRAAM, AIM-132 ASRAAM",
            "air-to-ground_missiles": "AGM-65 Maverick, AGM-88 HARM, AGM-129 ACM, JDAM",
            "bombs": "Mark 82, Mark 84, GBU-12 Paveway II, GBU-31 JDAM",
            "other": "AN/ALQ-128 electronic countermeasures pod, LANTIRN targeting pod",
        },
        "avionics": "Not specified",
        "length": 19.43,
        "speed": {"max_speed": "Mach 2.5+ (2,665 km/h; 1,653 mph)"},
        "maxrange": "Not specified",
        "engine": "Not specified",
        "climb_rate": "254 m/s (50,500 ft/min)",
        "missiles": "Not specified",
        "bombs": "Not specified",
    },
    {
        "name": "F-16 Fighting Falcon",
        "type": "Multirole fighter aircraft",
        "crew": "1",
        "weights": {
            "empty": "8,503 kg (18,751 lb)",
            "maximum_takeoff": "21,771 kg (48,000 lb)",
        },
        "range": {
            "ferry": "Not specified",
            "combat": "787 km (489 mi) (internal fuel), 3,229 km (2,006 mi) (with external tanks)",
        },
        "weapons": {
            "guns": "M61 Vulcan 20 mm cannon (670 rounds)",
            "missiles": "AIM-7 Sparrow, AIM-9 Sidewinder, AIM-120 AMRAAM, AIM-132 ASRAAM, AGM-65 Maverick, AGM-88 HARM, AGM-154 Joint Standoff Weapon (JSOW)",
            "bombs": "Mark 82, Mark 84, GBU-12 Paveway II, GBU-16 Paveway II, GBU-24 Paveway III, GBU-31/38 JDAM,",
            "pods": "LANTIRN targeting pod, Sniper targeting pod, AN/ALQ-131 electronic countermeasures pod",
        },
        "avionics": "Not specified",
        "length": "15.03",
        "speed": {"max_speed": "2,130 km/h (1,320 mph)"},
        "maxrange": "Not specified",
        "engine": "Not specified",
        "climb_rate": "254 m/s (50,000 ft/min)",
    },
    {
        "name": "Douglas F/A-18 Hornet",
        "type": "Multirole fighter aircraft",
        "crew": "1 or 2 (pilot and weapon systems officer)",
        "weights": {
            "empty": "14,740 kg (32,500 lb)",
            "maximum_takeoff": "29,100 kg (64,150 lb)",
        },
        "range": {
            "ferry": "Not specified",
            "combat": "970 km (597 mi) unrefueled, 3,300 km (2,050 mi) with external tanks",
        },
        "weapons": {
            "guns": "M61 Vulcan 20 mm cannon (670 rounds)",
            "missiles": "Air-to-air: AIM-120 AMRAAM, AIM-9 Sidewinder, AIM-7 Sparrow (retired), AIM-88 HARM (anti-radiation), AGM-84 Harpoon (anti-ship)",
            "bombs": "Mark 82, Mark 83, Mark 84, GBU-12 Paveway II, GBU-16 Paveway II, GBU-24 Paveway III, GBU-49 Paveway IV",
            "pods": "LANTIRN targeting pods, ALQ-100 electronic countermeasures pods",
        },
        "avionics": "Not specified",
        "length": "18.3",
        "speed": {"max_speed": "670 km/h (416 mph)"},
        "maxrange": "Not specified",
        "engine": "General Electric F404-GE-402 turbofan engines",
        "climb_rate": "152.4 m/s (499 ft/s)",
    },
    {
        "name": "F-22 Raptor",
        "type": "Fighter aircraft",
        "crew": "1",
        "weights": {
            "empty": "19,656 kg (43,332 lb)",
            "maximum_takeoff": "31,570 kg (69,601 lb)",
        },
        "range": {
            "ferry": "Not specified",
            "combat": "1,210 km (750 mi) with internal fuel",
        },
        "weapons": {
            "guns": "M61 Vulcan 20 mm (0.79 in) Gatling cannon with 480 rounds",
            "air-to-air missiles": "AIM-120 AMRAAM",
            "air-to-surface missiles": "AIM-9 Sidewinder, 2 × AGM-158 Joint Air-to-Surface Standoff Missile (JASSM), 2 × GBU-32 JDAM",
            "other": "AN/ALQ-128C Electronic Countermeasures System pods",
        },
        "avionics": "Not specified",
        "length": "19.5",
        "speed": {"max_speed": "2,410 km/h (1,490 mph)"},
        "maxrange": "Not specified",
        "engine": "Pratt & Whitney F119-PW-100 turbofan engines with afterburners",
        "climb_rate": "Not specified",
    },
    {
        "name": "F-35 Lightning II",
        "type": "fighter aircraft",
        "crew": 1,
        "weights": {"empty": "30,000 kg (66,000 lb)"},
        "range": {"ferry": "1200 km (750 mi)", "combat": "670 km (420 mi)"},
        "weapons": {
            "guns": "M38A1 25mm cannon",
            "missiles": "AIM-120 AMRAAM, AIM-9X Sidewinder, AIM-260 JATM",
            "bombs": "Mark 82, Mark 84, GBU-12 Paveway II",
        },
        "avionics": "AN/APG-81 Advanced Electronic Scan Radar (AESA), AN/ASQ-239 Data Transfer System (DTS), AN/ALQ-232 Countermeasures System",
        "length": 15.7,
        "speed": {"max_speed": "Mach 1.6"},
        "maxrange": "Not specified",
        "engine": "F135 turbofan engine",
        "climb_rate": "Not specified",
    },
    {
        "name": "McDonnell Douglas F-4 Phantom II",
        "type": "fighter-bomber",
        "crew": "Not specified",
        "weights": {
            "empty": "12,834 kg (28,300 lb)",
            "gross": "17,711 kg (39,045 lb)",
            "max takeoff": "25,401 kg (56,000 lb)",
        },
        "range": {
            "ferry": "Not specified",
            "combat": "1,480 km (920 mi) (internal fuel)",
        },
        "weapons": {
            "guns": ["M61 Vulcan 20mm cannon (later variants)"],
            "missiles": [
                "AIM-7 Sparrow",
                "AIM-9 Sidewinder",
                "AIM-120 AMRAAM (later variants)",
            ],
            "bombs": [
                "Mark 80 series",
                "Mark 82 series",
                "Rockeye Paveway laser-guided bombs",
            ],
        },
        "avionics": [
            "AN/APG-7 pulsed-Doppler radar",
            "AN/AWG-9 weapons system",
            "AN/ALQ-126 electronic countermeasures suite",
        ],
        "length": 19,
        "speed": {"max_speed": "2,370 km/h (Mach 2.23)"},
        "maxrange": "Not specified",
        "engine": "Not specified",
        "climb_rate": "152.4 m/s (499 ft/s)",
    },
    {
        "name": "Chengdu J-20",
        "type": "Fifth-generation jet fighter",
        "crew": 1,
        "weights": {
            "empty": "Not specified",
            "maximum_takeoff": "approximately 35,000 kg (estimated)",
        },
        "range": {
            "ferry": "Not specified",
            "combat": "long-range (specific range classified)",
        },
        "weapons": {
            "guns": "30mm Type 23-3 cannon (specific ammunition details classified)",
            "missiles": "various types and combinations (specific types and numbers classified)",
            "bombs": "limited capability (specific munitions classified)",
        },
        "avionics": {
            "radar": "advanced phased-array radar (specific capabilities classified)",
            "electronic countermeasures": "extensive suite (specific details classified)",
            "avionics suite": "highly integrated and advanced (specific systems classified)",
        },
        "length": 23,
        "speed": {"max_speed": "supersonic (specific speed classified)"},
        "maxrange": "Not specified",
        "engine": "Not specified",
        "climb_rate": "Not specified",
    },
    {
        "name": "Saab JAS 39 Gripen",
        "type": "multirole fighter aircraft",
        "crew": "Not specified",
        "weights": {
            "empty": "8,500 kg (18,700 lb)",
            "maximum_takeoff": "16,500 kg (36,400 lb)",
        },
        "range": {"ferry": "1,300 km (810 mi)", "combat": "Not specified"},
        "weapons": {
            "guns": "27 mm (1.06 in) Mauser BK-27 cannon",
            "missiles": "AIM-120 AMRAAM, IRIS-T, MBDA Meteor, AIM-9 Sidewinder, Rb74, etc.",
            "bombs": "Mk 82, Mk 84, GBU-12 Paveway II, etc.",
        },
        "avionics": "Not specified",
        "length": 14.8,
        "speed": {"max_speed": "Mach 2.0 (2,469 km/h; 1,534 mph)"},
        "maxrange": "Not specified",
        "engine": "Not specified",
        "climb_rate": "250 m/s (787 ft/s)",
    },
    {
        "name": "MQ-9 Reaper",
        "type": "Unmanned aerial vehicle (UAV)",
        "crew": "Not applicable",
        "weights": {
            "empty": "5,443 kg (12,000 lb)",
            "maximum_takeoff": "Not specified",
        },
        "range": {"ferry": "3,170 km (1,970 mi)", "combat": "Not specified"},
        "weapons": [
            "AGM-114 Hellfire missiles",
            "GBU-12 Paveway II laser-guided bombs",
            "Mk 82 air bombs",
            "AIM-92 Stinger air-to-air missiles",
        ],
        "avionics": "Not specified",
        "length": 11,
        "speed": {"max_speed": "270 km/h (168 mph)"},
        "maxrange": "Not specified",
        "engine": "Rolls-Royce AE-130 turboprop engine",
        "climb_rate": "Not specified",
    },
    {
        "name": "Mikoyan MiG-31",
        "type": "Interceptor, multirole (MiG-31BM)",
        "crew": "Not specified",
        "weights": {
            "empty": "46,150 kg (101,754 lb)",
            "maximum_takeoff": "79,500 kg (175,316 lb)",
        },
        "range": {"ferry": "2,300 km (1,400 mi)", "combat": "Not specified"},
        "weapons": {
            "guns": "30 mm GSh-31-1 cannon (260 rounds)",
            "missiles": {
                "air-to-air": [
                    "R-33 (AA-9 Amos)",
                    "R-37 (AA-10 Alamo)",
                    "R-60 (AA-8 Aphid)",
                    "R-40 (AA-6 Krypton)",
                    "Kh-47M2 Kinzhal (hypersonic)",
                ],
                "air-to-surface": "Kh-59 (AS-13 Kingfish)",
            },
        },
        "avionics": {
            "radar": "Zaslon-M phased-array radar, detection range up to 300 km (190 mi)",
            "electronic_countermeasures": "Khibiny-M electronic countermeasures suite",
        },
        "length": 23,
        "speed": {"max_speed": "Mach 2.83 (3,000 km/h, 1,864 mph)"},
        "maxrange": "Not specified",
        "engine": "Not specified",
        "climb_rate": "126 m/s (413 ft/s)",
    },
    {
        "name": "Dassault Aviation Fighter",
        "type": "fighter aircraft",
        "crew": "Not specified",
        "weights": {"empty": "7500 kg", "maximum_takeoff": "17500 kg"},
        "range": {"ferry": "1850 km", "combat": "900 km"},
        "weapons": {
            "guns": [
                {
                    "type": "DEFA 554",
                    "caliber": "30 mm",
                    "rounds_per_minute": "1200-1800",
                }
            ],
            "missiles": ["MICA IR", "MICA EM", "Black Shaheen cruise missile"],
            "bombs": ["conventional", "video-guided", "laser-guided"],
            "pods": ["recce", "laser designation"],
        },
        "avionics": {
            "radar": "Thales RDY-2",
            "navigation": ["inertial", "GPS", "data-link"],
            "cockpit": [
                "glass cockpit",
                "head-up display",
                "multifunction displays",
                "night vision goggles compatibility",
            ],
        },
        "length": 14,
        "speed": {"max_speed": "2352 km/h (Mach 2.2+)"},
        "maxrange": "Not specified",
        "engine": "SNECMA M53-P2 turbofan engine (1x)",
        "climb_rate": "60000 ft/min",
    },
    {
        "name": "Lockheed P-3 Orion",
        "type": "Maritime patrol, reconnaissance, anti-submarine warfare",
        "crew": "Not specified",
        "weights": {
            "empty": "73,400 lb (33,300 kg)",
            "maximum_takeoff": "147,000 lb (66,700 kg)",
        },
        "range": "2,500 miles (4,000 km)",
        "weapons": {
            "missiles": "AGM-84 Harpoon anti-ship missiles, Mark 46 torpedoes, AGM-12 Bullpup air-to-ground missiles",
            "guns": "20mm M61 Vulcan cannon, .50 caliber machine guns",
            "depth charges": "MK 54/60/106 depth charges",
        },
        "avionics": {
            "radar": "AN/APS-131 long-range search radar, AN/APS-128 tactical surveillance radar",
            "sonar": "AN/AQS-13C dipping sonar, AN/BQQ-1 acoustic processor",
            "electronic countermeasures": "AN/ALR-62 radar warning receiver, AN/ALR-21 ESM system",
        },
        "length": 35.61,
        "speed": {"max_speed": "411 mph (661 km/h)"},
        "maxrange": "Not specified",
        "engine": "Allison T56-A-14 turboprop engine (4x)",
        "climb_rate": "Not specified",
    },
    {
        "name": "Northrop Grumman UAV",
        "type": "high-altitude, long-endurance (HALE) unmanned aerial vehicle (UAV)",
        "crew": "Not specified",
        "weights": {"empty": "Not specified", "maximum_takeoff": "14,672 kilograms"},
        "range": "22,780 kilometers",
        "weapons": "none",
        "avionics": {
            "radar": {
                "type": "Synthetic Aperture Radar (SAR)",
                "ground_resolution": "0.3 meters",
            },
            "electro-optical/infrared (EO/IR)": {
                "daytime_resolution": "0.6 meters",
                "nighttime_resolution": "1.2 meters",
            },
        },
        "length": 14,
        "speed": {"max_speed": "Not specified"},
        "maxrange": "Not specified",
        "engine": "Rolls-Royce AE3007 turbofan engine (1x)",
        "climb_rate": "Not specified",
    },
    {
        "name": "Dassault Rafale",
        "type": "multirole fighter aircraft",
        "crew": "Not specified",
        "weights": {
            "empty": "9,500 kg (20,944 lb)",
            "maximum_takeoff": "24,500 kg (54,013 lb)",
        },
        "range": {
            "ferry": "3,700 km (2,300 mi) with 2 external fuel tanks",
            "combat": "Not specified",
        },
        "weapons": {
            "guns": "30 mm (1.18 in) GIAT DEFA cannon (internal)",
            "missiles": {
                "short-range": "MBDA Mica IR/RF, Thales IRIS-T, Meteor (future)",
                "medium-range": "MBDA Mongoose, MBDA Meteor",
                "long-range": "MBDA Meteor",
            },
            "bombs": {
                "guided": "MBDA AASM hammer, GBU-24 Paveway III, GBU-49 Paveway II",
                "unguided": "Mk.82 JDAM, GBU-12 Paveway II, GBU-16 Paveway II",
            },
            "other": "Laser targeting pods, reconnaissance pods, electronic warfare pods",
        },
        "avionics": "Snecma M88-2E turbofan engines",
        "length": 15,
        "speed": {"max_speed": "2,125 km/h (Mach 1.8)"},
        "maxrange": "Not specified",
        "engine": "Not specified",
        "climb_rate": "Not specified",
    },
    {
        "name": "Lockheed SR-71 Blackbird",
        "type": "Long-range, high-altitude reconnaissance aircraft",
        "crew": "Not specified",
        "weights": {
            "empty": "77,113 kg (170,000 lb)",
            "maximum_takeoff": "340,194 kg (750,000 lb)",
        },
        "range": "5470 km (3400 mi)",
        "weapons": {
            "internal": "20mm M61 Vulcan cannon (optional)",
            "external": "AIM-120 AMRAAM air-to-air missiles (prototypes only)",
        },
        "avionics": {
            "radar": "APG-28 pulse-doppler radar",
            "navigation": "inertial navigation system (INS)",
            "electronic countermeasures": "AN/ALQ-121 ECM system",
        },
        "length": 33,
        "speed": {"max_speed": "3,540 km/h (Mach 3.3)"},
        "maxrange": "Not specified",
        "engine": {"type": "Pratt & Whitney J58 afterburning turbojet", "number": 2},
        "climb_rate": "Not specified",
    },
    {
        "name": "Sukhoi Su-34",
        "type": "twin-seat, all-weather, supersonic, medium-range strike fighter/bomber",
        "crew": "Not specified",
        "weights": {
            "empty": "42,580 kg (94,000 lb)",
            "maximum_takeoff": "73,600 kg (162,300 lb)",
        },
        "range": {
            "unrefueled": "1,100 km (683 mi)",
            "aerial_refueling": "4,000 km (2,485 mi)",
        },
        "weapons": {
            "guns": "GSh-30-1 30 mm (1.18 in) cannon with 150 rounds",
            "hardpoints": "6 under each wing) with a total payload capacity of 8,000 kg (17,637 lb)",
            "weapons": [
                "air-to-air missiles (R-73, R-27, RVV-AE)",
                "air-to-surface missiles (Kh-31, Kh-59, Kh-25L, KAB-500)",
                "guided bombs (KAB-250, KAB-500)",
                "unguided bombs (FAB-500, FAB-250)",
                "rockets",
                "electronic warfare pods",
            ],
        },
        "avionics": "N-037E radar, GLONASS/GPS navigation system, passive electronic countermeasures, integrated defensive aids suite",
        "length": 23,
        "speed": {"max_speed": "1,900 km/h (Mach 1.65)"},
        "maxrange": "Not specified",
        "engine": "AL-31F turbofan engines with 137.9 kN (31,100 lbf) thrust each",
        "climb_rate": "58.5 m/s (1,161 ft/min)",
    },
    {
        "name": "Sukhoi Su-57",
        "type": "fighter aircraft",
        "crew": "Not specified",
        "weights": {
            "empty": "18,000 kg (39,683 lb)",
            "maximum_takeoff": "35,000 kg (77,165 lb)",
        },
        "range": {"ferry": "2,100 km (1,300 mi)", "combat": "1,200 km (746 mi)"},
        "weapons": {
            "guns": "30 mm (1.18 in) GSh-30-1 internal cannon with 150 rounds",
            "missiles": [
                "R-77 (RVV-AE) medium-range active radar homing",
                "K-7M3 (RVV-MD) medium-range active radar homing",
                "R-37M (RVV-BD) long-range active radar homing",
                "R-73 (RVV-SD) short-range infrared homing",
            ],
            "bombs": "FAB-500M (2,200 lb)",
        },
        "avionics": {
            "radar": "N036 Pesnya-E phased-array radar",
            "electronic_countermeasures": "Khibiny-M electronic warfare suite",
        },
        "length": 18.70,
        "speed": {"max_speed": "2,500 km/h (1,550 mph)"},
        "maxrange": "Not specified",
        "engine": "AL-41F1 turbofan engines with afterburning thrust of 147 kN (33,000 lbf) each",
        "climb_rate": "Not specified",
    },
    {
        "name": "Panavia Tornado",
        "type": "Multirole combat aircraft",
        "crew": "pilot and navigator/weapons system officer",
        "weights": {
            "empty": "Not specified",
            "maximum_takeoff": "31,000 kg (68,343 lb)",
        },
        "range": {
            "ferry": "2,900 km (1,800 mi)",
            "combat": "735 km (457 mi) with two AIM-120 AMRAAMs and four 500 lb bombs",
        },
        "weapons": {
            "guns": "Not specified",
            "missiles": ["AIM-120 AMRAAM", "AIM-9 Sidewinder", "IRIS-T", "Meteor"],
            "bombs": [
                "Mk 82, 83, 84",
                "GBU-12 Paveway II",
                "BL755 Cluster Bomb",
                "WEP 1100 Cluster Bomb",
            ],
            "air-to-surface_missiles": [
                "AGM-65 Maverick",
                "AGM-88 HARM",
                "ALARM",
                "JP233",
            ],
            "reconnaissance_pods": ["RecceLite", "TIALD", "LITENING"],
        },
        "avionics": [
            "multimode radar",
            "laser rangefinder",
            "inertial navigation system",
            "electronic countermeasures suite",
        ],
        "length": 18.68,
        "speed": {"max_speed": "Not specified"},
        "maxrange": "Not specified",
        "engine": "(2 x Turbo-Union RB199 Mk 105 afterburning turbofans, 4,400 kg (9,700 lb) thrust each)",
        "climb_rate": "Not specified",
    },
    {
        "name": "Tupolev Tu-160",
        "type": "Supersonic strategic bomber",
        "crew": "Not specified",
        "weights": {"empty": "108,000 kg", "maximum_takeoff": "275,000 kg"},
        "range": {"ferry": "13,900 km (unrefueled)", "combat": "Not specified"},
        "weapons": {
            "internal_weapons_bay": {
                "capacity": "15,000 kg (33,000 lb) of ordnance",
                "compatible_weapons": [
                    "Kh-55 (AS-15) long-range cruise missiles",
                    "Kh-101 (AS-23) nuclear-capable cruise missiles",
                    "Kh-SD (AS-16) ballistic missiles",
                    "FAB-500M62 high-explosive bombs",
                ],
            },
            "rotary_launcher": {
                "capacity": "Kh-15P (AS-17) short-range nuclear missiles"
            },
        },
        "avionics": {
            "radar": "K-30A multi-mode radar",
            "navigation_system": "INS-2M inertial navigation system",
            "electronic_countermeasures": "L-370 SVP-25 electronic countermeasures suite",
        },
        "length": 34.5,
        "speed": {"max_speed": "2,500 km/h (Mach 2.05)"},
        "maxrange": "Not specified",
        "engine": "Kuznetsov NK-32 turbofan engines with thrust of 51,000 kg (112,000 lb) per engine",
        "climb_rate": "Not specified",
    },
    {
        "name": "Tupolev Tu-95",
        "type": "strategic bomber",
        "crew": "Not specified",
        "weights": {
            "empty": "90,000 kg (198,416 lb)",
            "maximum_takeoff": "185,000 kg (407,855 lb)",
        },
        "range": {
            "ferry": "15,000 km (9,320 mi) (with one refueling)",
            "combat": "Not specified",
        },
        "weapons": {
            "guns": "Not specified",
            "missiles": "Kh-22 (NATO codename: AS-4 Kitchen) cruise missiles (Tu-95MS only), up to 6 × Kh-55 (NATO codename: AS-15 Kent) cruise missiles (Tu-95MC only)",
            "bombs": "up to 15,000 kg (33,069 lb) of conventional bombs, including FAB-500 M62, FAB-250-M62, and FAB-500M-64",
        },
        "avionics": "Vega-M navigation and attack system, Obzor-MS radar, Khibiny electronic countermeasures",
        "length": 46,
        "speed": {"max_speed": "925 km/h (575 mph)"},
        "maxrange": "Not specified",
        "engine": "Kuznetsov NK-12 turboprop engines, 11,000 kW (14,795 hp) each",
        "climb_rate": "Not specified",
    },
    {
        "name": "U-2S Dragon Lady",
        "type": "High-altitude reconnaissance",
        "crew": "Not specified",
        "weights": {
            "empty": "39,000 lb (17,700 kg)",
            "maximum_takeoff": "65,000 lb (29,500 kg)",
        },
        "range": "6,200 miles (10,000 km+)",
        "weapons": "None",
        "avionics": {
            "sensors": [
                "Electro-optical cameras",
                "Infrared cameras",
                "Radar",
                "Signal intelligence systems",
                "Electronic intelligence systems",
            ],
            "navigation_and_communication": [
                "Inertial navigation system",
                "GPS",
                "Secure data links",
                "Voice and data communication systems",
            ],
        },
        "length": 63,
        "speed": {"max_speed": "500 mph (805 km/h)"},
        "maxrange": "Not specified",
        "engine": "General Electric F118-GE-100",
        "climb_rate": "Not specified",
    },
    {
        "name": "ShinMaywa US-2",
        "type": "Amphibious aircraft (STOL)",
        "crew": "Not specified",
        "weights": {"empty": "25,630 kg", "maximum_takeoff": "45,200 kg"},
        "range": {"ferry": "5,600 km (3,480 mi)", "combat": "4,700 km (2,920 mi)"},
        "weapons": "Not applicable",
        "avionics": "Not specified",
        "length": 33.2,
        "speed": {"max_speed": "560 km/h (342 mph)"},
        "maxrange": "Not specified",
        "engine": {
            "type": "Turboprop",
            "model": "Rolls-Royce AE 2100D",
            "number": 4,
            "power": "4,628 kW (6,230 shp) each",
        },
        "climb_rate": "Not specified",
    },
    {
        "name": "Bell Boeing V-22 Osprey",
        "type": "Multi-mission tiltrotor aircraft",
        "crew": "Not specified",
        "weights": {"empty": "14,915 kg", "maximum_takeoff": "27,216 kg"},
        "range": "841 km",
        "weapons": {
            "guns": "Not specified",
            "missiles": "Not specified",
            "bombs": ["Machine guns", "Rockets", "Missiles", "Bombs"],
        },
        "avionics": {
            "radar": "AN/APG-70 radar",
            "navigation": "AN/ARN-21B TACAN, AN/ARN-118A IFF, AN/PLX-21C GPS",
            "electronic_warfare": "AN/ALR-67(V)3 ESM, AN/APR-39C(V) RWR",
        },
        "length": 17,
        "speed": {"max_speed": "565 km/h"},
        "maxrange": "Not specified",
        "engine": {
            "type": "Rolls-Royce T406-GE-426 turboprop",
            "number": 2,
            "power": "5,510 shp each",
        },
        "climb_rate": "Not specified",
    },
    {
        "name": "Avro Vulcan",
        "type": "bomber",
        "crew": "Not specified",
        "weights": {
            "empty": "20,400 kg (44,980 lb)",
            "maximum_takeoff": "45,450 kg (100,200 lb)",
        },
        "range": "4,450 km (2,760 mi) with high-altitude bombing load",
        "weapons": {
            "guns": "Not specified",
            "missiles": {"Blue_Steel": "Nuclear weapon"},
            "bombs": {
                "maximum_payload": "9,072 kg (20,000 lb) of conventional bombs",
                "specific_examples": [
                    "21 x 454 kg (1,000 lb) bombs",
                    "1 x 4,540 kg (10,000 lb) bomb",
                ],
            },
        },
        "avionics": "Not specified",
        "length": 27.6,
        "speed": {"max_speed": "1,040 km/h (646 mph)"},
        "maxrange": "Not specified",
        "engine": {
            "type": "Four Rolls-Royce Olympus 201 turbofan engines",
            "thrust": "17,230 kN (3,850 lbf) each",
        },
        "climb_rate": "Not specified",
    },
    {
        "name": "XB-70 Valkyrie",
        "type": "Supersonic bomber prototype",
        "crew": "Not specified",
        "weights": {
            "empty": "115,000 kg (253,537 lb)",
            "maximum_takeoff": "272,000 kg (599,677 lb)",
        },
        "range": {"ferry": "7,200 km (4,470 miles)", "combat": "Not specified"},
        "weapons": {
            "guns": "None (prototype only)",
            "missiles": "Nuclear bombs, missiles, and conventional bombs",
            "bombs": "Not specified",
        },
        "avionics": {
            "flight_control_system": "Analog",
            "radar": "AN/ASG-18 bombing-navigation radar",
            "communication": "AN/ARC-38 HF radio, AN/ARC-58 VHF radio",
        },
        "length": 57,
        "speed": {"max_speed": "Mach 3.3 (3,309 km/h, 2,056 mph)"},
        "maxrange": "Not specified",
        "engine": {
            "type": "Turbojet",
            "model": "General Electric YJ93-GE-3",
            "quantity": 6,
            "thrust": "158 kN (35,000 lbf) per engine",
        },
        "climb_rate": "Not specified",
        "missles": "Not specified",
        "bombs": "Not specified",
    },
    {
        "name": "Northrop YF-23",
        "type": "Air superiority fighter",
        "crew": 1,
        "weights": {
            "empty": "13,420 kg (29,600 lb)",
            "maximum_takeoff": "27,200 kg (60,000 lb)",
        },
        "range": {
            "ferry": "Unofficial estimates suggest 1,400 km (870 mi)",
            "combat": "Not specified",
        },
        "weapons": {
            "guns": "1 x 20 mm M61 Vulcan cannon",
            "missiles": "4 x AIM-120 AMRAAM or AIM-7 Sparrow medium-range air-to-air missiles",
            "bombs": "Internal weapons bay for additional missiles and bombs (unconfirmed)",
        },
        "avionics": [
            "AN/APG-73 radar",
            "AN/ALQ-131 electronic warfare suite",
            "AN/AWACS data link",
        ],
        "length": 21,
        "speed": {"max_speed": "Mach 2.5 (2,600 km/h, 1,600 mph)"},
        "maxrange": "Not specified",
        "engine": [
            "2 x Pratt & Whitney YF119 or General Electric YF120 turbofan engines",
            "each with 156 kN (35,000 lbf) of thrust",
        ],
        "climb_rate": "305 m/s (1,000 ft/s)",
        "missles": "Not specified",
        "bombs": "Not specified",
    },
]
